---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/PST
    volumes:
      - /home/sean/docker/radarr:/config
        # - /lake/movies/Movies:/movies
        # - /lake/tv/TV:tv
        # - /path/to/downloadclient-downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
