version: "3.9"
services:
  kavita:
    image: kizaing/kavita:latest
    volumes:
      - /lake/manga:/manga
      - /opt/stacks/kavita/data:/kavita/config
    ports:
      - 5000:5000
    restart: unless-stopped
networks: {}
