---
services:
  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest
    environment:
      - AUDIOBOOKSHELF_UID=99
      - AUDIOBOOKSHELF_GID=100
    ports:
      - 13378:80
    volumes:
      - /opt/audiobook/media/volume1/Media/books.audio:/audiobooks
      - /opt/audiobook/media/volume1/Media/radio.podcasts:/podcasts
      - /opt/audiobook/config>:/config
      - /opt/audiobook/metadata>:/metadata