version: "3"
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:9999
    environment:
      - DOZZLE_ADDR=:9999
      - DOZZLE_NO_ANALYTICS=true