version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/PST
      - VERSION=docker
      - PLEX_CLAIM=claim-vvEeszjfNdzFF87dGVs8
    volumes:
      - /opt/stacks/plex:/config
      - /lake/tv:/tv
      - /lake/movies:/movies
    restart: unless-stopped
networks: {}
